USE campaign_db;
-- CREATING A TABLE AND IMPORTING THE DATA USING TABLE DATA IMPORT WIZARD --

SELECT COUNT(*) FROM marketing;
SELECT DISTINCT campaign_name FROM marketing;
SELECT DISTINCT category FROM marketing;

SELECT * FROM marketing
WHERE 
		c_date IS NULL OR campaign_name IS NULL OR category IS NULL;
	

-- Q1 WHICH COMPAIGNS DELIVERS THE BEST RETURN ON INVESTMENT --

SELECT campaign_name, 
		ROUND((revenue/expenditure)*100,2) AS 
        ROI FROM (
					SELECT campaign_name,SUM(mark_spent) AS expenditure,
                    SUM(revenue) AS Revenue FROM marketing
					GROUP BY 1) AS t1
ORDER BY 2 DESC;

-- YOUTUBE_BLOGGER CAMPAIGN GAVE THE ROI OF ABOUT 377% AND IS THE MOST SUCCESSFULL CAMAPIGN  WITH A HUGE MARGIN, 2ND BEING FACEBOOK_RETARGETING WITH 201% ROI --
-- WHILE INSTAGRAM_TIER2 IS THE MOST UNSUCCESFULL CAMAPIGN WITH ROI OF ONLY 63%. -- 
-- WITH ROI < 100 % ROI FACEBOOK_TIER1,FACEBOOK_TIER2,GOOGLE_WIDE,INSTAGRAM_TIER2 CAN BE CONSIDERED AS UNSUCCESSFULL CAMPAINGS --

-- Q2 WHAT IS THE AVERAGE COST TO ACQUIRE A LEAD OR AN ORDER --

SELECT campaign_name,
		ROUND(SUM(mark_spent)/sum(leads),2) AS expense_perlead,
        RANK () OVER (ORDER BY ROUND(SUM(mark_spent)/sum(leads),2) ) as leads_ranks, 
        ROUND(SUM(mark_spent)/sum(orders),2) AS expense_perorder,
        RANK() OVER (ORDER BY ROUND(SUM(mark_spent)/sum(orders),2) ) AS order_ranks
        FROM marketing
GROUP BY 1
ORDER BY 3,5;

-- LEAD CAN BE GENERATED BY INSTAGRAM_TIER2 CAMPAIGN WITH VERY LESS EXPENSE BUT THOSE LEADS RARELY GETS CONVERTS INTO ORDER --
-- WHILE LEAD GET CONVERTED INTO ORDER VERY EASILY WITH YOUTUBE_BLOGGER CAMPAIGN -- 



-- Q3 WHAT IS THE AVERAGE COST TO ACQUIRE ORDER BY CATEGORY --

SELECT 
		category,
        ROUND(SUM(mark_spent)/sum(leads),2) AS expense_perlead,
        ROUND(SUM(mark_spent)/sum(orders),2) AS expense_perorder
        FROM marketing
GROUP BY 1
ORDER BY 3;

-- WHAT IS THE AVERAGE COST TO ACQUIRE ORDER BY CAMPAIGNS --
SELECT 
		campaign_name,
        ROUND(SUM(mark_spent)/sum(leads),2) AS expense_perlead,
        ROUND(SUM(mark_spent)/sum(orders),2) AS expense_perorder
        FROM marketing
GROUP BY 1
ORDER BY 3;

-- HERE WE CAN SEE THE SOCAIL CATEGORY GENERATES THE LEADS VERY EASILY, BUT RARELY IT GETS CONVERTED INTO ORDER -- 
-- WHILE LEAD GENERATED THROUGH INFLUENCERS GETS CONVERTED INTO ORDER BY BETTER RATE AS COMPARED TO OTHER CATEGORY --

-- Q4 CONVERSION RATE FROM LEADS TO ORDER BY CATEGORY AND CAMPAIGNS --

SELECT category,
	(SUM(ORDERS)/SUM(LEADS))*100 AS conversion_rate
	FROM marketing
GROUP BY 1
ORDER BY 2 DESC;

SELECT campaign_name,
	(SUM(ORDERS)/SUM(LEADS))*100 AS conversion_rate
	FROM marketing
GROUP BY 1
ORDER BY 2 DESC;

-- THE INFLUENCER CONVERSION RATE STANDS TOP WITH OVER 17%, WHILE SOCIAL REMAINS LOW AT 8 % --

SELECT campaign_name,
	(SUM(ORDERS)/SUM(LEADS))*100 AS conversion_rate
	FROM marketing
GROUP BY 1
ORDER BY 2 DESC;

-- THE CONVERSION RATE FROM ORDER TO LEADS FACEBOOK_RETARGETING STANDS TOP WITH OVER 21% WHILE INSTAGRAM TIER_2 STANDS LOWEST WITH JUST OVER 3% --


-- Q5 WHICH CAMAPIGN HAS THE BEST CLICK THROUGH RATE -- 

SELECT 
	campaign_name,
    ROUND((SUM(clicks)/SUM(impressions))*100,2) AS CTR FROM marketing
WHERE impressions>0
GROUP BY 1
order by 2 desc;

-- CLICK THROUGH RATE FOR FACEBOOK_RETARGETING STANDS TOP WITH 3% WHILE BANNER_PARTNER CAMPAIGN HAS THE LOWEST WITH JUST 0.03% CTR --

SELECT 
	category,
	ROUND((SUM(clicks)/SUM(impressions))*100,2) AS CTR FROM marketing
WHERE impressions>0
GROUP BY 1
ORDER BY 2 DESC;

-- CLICK THROUGH RATE FOR INFLUENCER STANDS TOP WITH 1% WHILE MEDIA CATEGORY HAS THE LOWEST WITH JUST 0.04% CTR --


-- Q6 THE PERCENTAGE OF CONVERSION FROM EACH FIELD -- 
select 
	category,
    ROUND((SUM(clicks)/SUM(impressions))*100,2) AS clicks_per_impression,
    ROUND((SUM(leads)/SUM(clicks))*100,2) AS leads_per_clicks,
    ROUND((SUM(orders)/SUM(leads))*100,2) AS orders_per_leads
    FROM marketing
GROUP BY 1
ORDER BY 4 DESC;

-- THE RATE OF LEADS PER CLICK IS ALMOST SAME WITH EVERY CATEGORY WITH VERY LITTLE DIFFERENCE.-- 
-- BUT THE CONVERSION FROM THAT LEADS HAS A NOTABLE DIFFERENCES --

-- Q7 DAILY PERFORMANCE TRENDS --

SELECT 
	c_date,
    ROUND(SUM(mark_spent),0) AS expenses,
    SUM(revenue) AS revenue,
    SUM(orders) AS total_orders,
    ROUND(SUM(mark_spent)/SUM(orders),0) AS per_order_expense
    FROM marketing
GROUP BY 1;

-- Q8 TOP SPENDING V/S TOP EARNING CAMPAIGNS --

SELECT 
	category,
    ROUND(SUM(mark_spent),0) as mark_spent,
    RANK() OVER(ORDER BY SUM(mark_spent) DESC) AS expense_rank,
	ROUND(SUM(revenue),0) AS revenue,
    RANK() OVER(ORDER BY SUM(revenue)DESC) AS revenue_rank,
    ROUND((SUM(revenue)/SUM(mark_spent))*100,0)AS ROI
    FROM marketing
GROUP BY 1;

-- ROI IS MUCH HIGH IN INFLUENCER CATEGORY AND POTENTIALLY BE ONLY SUCCESSFULL CATEGORY, WHILE REMAINING ALL CATEGORY IS JUST OVER OR UNDER 100 --

SELECT 
	campaign_name,
    ROUND(SUM(mark_spent),0) as mark_spent,
    RANK() OVER(ORDER BY SUM(mark_spent) DESC) AS expense_rank,
	ROUND(SUM(revenue),0) AS revenue,
    RANK() OVER(ORDER BY SUM(revenue)DESC) AS revenue_rank,
    ROUND((SUM(revenue)/SUM(mark_spent))*100,0)AS ROI
    FROM marketing
GROUP BY 1
ORDER BY 6 DESC;

-- YOUTUBE_BLOGGER GIVING A HIGHEST ROI NEARLY TWICE FROM THE SECOND BEST, WHILE MORE THAN 5 CATEGORIES COULDN'T EVEN GET THE INVESTED MONEY BACK --
-- FACEBOOK_LAL CAMPAIGN HAS JUST ROI OF 11 -- 

-- Q9 WHICH ADVERTISING CHANNEL GIVES BEST PROFIT MARGIN--

SELECT category,
		ROUND(SUM(revenue)-SUM(mark_spent),0) AS profit_margin 
        FROM marketing
GROUP BY 1
ORDER BY 2 DESC;

--  WHICH CAMPAIGN GIVES US BEST PROFIT MARGIN--

SELECT campaign_name,
		ROUND(SUM(revenue)-SUM(mark_spent),0) AS profit_margin 
        FROM marketing
GROUP BY 1
ORDER BY 2 DESC;

-- Q10 THE CAMAPIGN WHICH HAS ZERO REVENUE --

SELECT campaign_name,COUNT(*) AS number_of_days,
		SUM(mark_spent) AS expense 
        FROM marketing
WHERE revenue=0 OR orders = 0
GROUP BY 1
ORDER BY 3 DESC;

-- TOTAL 19 CAMAPIGNS WENT WITH ZERO REVENUE --

SELECT DAYNAME(c_date),COUNT(*) AS number_of_days,
		SUM(mark_spent) AS expense 
        FROM marketing
WHERE revenue=0 OR orders = 0
GROUP BY 1
ORDER BY 2 DESC;


-- IN SATURDAY 6 CAMAPIGNS WENT WITH ZERO ORDERS EVEN THE EXPENSE ON THOSE DAY FOR THOSE CAMPAINGS WENT ABOVE 10K -- 


-- Q11 WHAT IS THE GROWTH OVER DAY ON EACH DAY FOR EACH CAMPAIGNS -- 


SELECT
    campaign_name,
    c_date,
    DAYNAME(c_date) AS dayname,
    revenue,
    LAG(revenue) OVER (
        PARTITION BY campaign_name
        ORDER BY c_date
    ) AS prev_day_revenue,
    -- % change compared to previous day
    ROUND(
        ( (revenue - LAG(revenue) OVER (
                PARTITION BY campaign_name
                ORDER BY c_date
            )
          ) / NULLIF(LAG(revenue) OVER (
                PARTITION BY campaign_name
                ORDER BY c_date
            ), 0)
        ) * 100, 2
    ) AS revenue_growth_pct
FROM marketing
ORDER BY campaign_name, c_date;

-- THE GROWTH RATE BY EACH PASSING DAY COMPARED TO PREVIOUS DAY CAN BE SEEN IN THE TABLE THERE IS NO TRENDS THAT CAN BE SEEN --

-- Q12 OVERALL CONVERSION RATES FROM LEADS --
SELECT 
	(SUM(orders)/SUM(leads))*100 AS total_avg 
    FROM marketing;

-- TOTAL LEAD CONVERSION RATES STANDS AT 12% --

-- Q13 ON WHICH DAY HIGHEST REVENUE GENERERATED AND HIGHEST ROI RECORDED ON WHICH DAY-- 
SELECT 
    DAYNAME(c_date) AS weekname,
    SUM(revenue)   AS total_revenue,
    ROUND(SUM(mark_spent),0) as expense,
    ROUND((sum(revenue)/sum(mark_spent))*100,0) as ROI
FROM marketing
GROUP BY DAYNAME(c_date)
ORDER BY ROI DESC;

-- FRIDAY HAS THE HIGHEST ROI FOLLOWED BY SATURDAY, SUNDAY HAS THE LOWEST ROI AMONG ALL THE DAYS -- 

-- Q14 ON WHICH DAY A PARTICULAR CAMPAIGN HAS RECORDED HIGHEST ROI--

SELECT * FROM marketing;
WITH ranking_days AS (
SELECT campaign_name,
		DAYNAME(c_date) AS dayname,
        ROUND((SUM(revenue)/SUM(mark_spent)*100),2) AS ROI,
        DENSE_RANK() OVER (PARTITION BY campaign_name ORDER BY SUM(revenue)/SUM(mark_spent) DESC) AS ranks
        FROM marketing
GROUP BY 1,2) 

SELECT * FROM ranking_days 
WHERE ranks=1 
ORDER BY 3 DESC;

-- HERE WE CAN SEE FOR WHICH CAMPAIGN WHICH DAY WOULD GIVE BETTER RESULTS --
-- AS WE HAVE SEEN EARLIER MOST OF THESE ARE SATURDAYS BUT WE CAN ALSO SEE FRIDAY,TUESDAY, MONDAY AS WELL --


        

















